# Site settings
title: blog
email: chouhom7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  一个博客而已
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.chouhom.com" # the base hostname & protocol for your site
twitter_username: homchou
github_username:  homchou

# Build settings
markdown: kramdown
#markdown: redcarpet
